name: Run BoatPirate Script

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-boat-pirate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: staging
      cancel-in-progress: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run BoatPirate script
      run: python boat_pirate.py

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add boat_models.csv
        git commit -m "Newly pirated boats $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}